# Generated by Django 5.2.17 on 2026-08-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0003_ticket_on_hold_at_ticket_total_hold_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolution_breached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='response_breached',
            field=models.BooleanField(default=False),
        ),
    ]
